version: "2"

services:
  app:
    build:
      context: .
    command: 'bundle exec rails s puma -p 3000 -b 0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      - "DEVELOPMENT_DATABASE_URL=postgres://postgres@postgres/welevel_ruby_test_development"
      - "TEST_DATABASE_URL=postgres://postgres@postgres/welevel_ruby_test_test"
    depends_on:
      - "postgres"
    volumes:
      - .:/welevel_ruby_test
    volumes_from:
      - bundle_box
    tty: true
    stdin_open: true

  postgres:
    image: "postgres:9.6.2"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  bundle_box:
    image: busybox
    volumes:
      - /bundle_box

volumes:
  postgresql-data:
